/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.github.y_samy.gui;

/**
 *
 * @author youssef
 */
public class NbAbstractBoardView extends javax.swing.JPanel {

    /**
     * Creates new form AbstractBoardView
     */
    public NbAbstractBoardView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        cell1 = new javax.swing.JToggleButton();
        cell2 = new javax.swing.JToggleButton();
        cell3 = new javax.swing.JToggleButton();
        cell4 = new javax.swing.JToggleButton();
        cell5 = new javax.swing.JToggleButton();
        cell6 = new javax.swing.JToggleButton();
        cell7 = new javax.swing.JToggleButton();
        cell8 = new javax.swing.JToggleButton();
        cell9 = new javax.swing.JToggleButton();
        cell10 = new javax.swing.JToggleButton();
        cell11 = new javax.swing.JToggleButton();
        cell12 = new javax.swing.JToggleButton();
        cell13 = new javax.swing.JToggleButton();
        cell14 = new javax.swing.JToggleButton();
        cell15 = new javax.swing.JToggleButton();
        cell16 = new javax.swing.JToggleButton();
        cell17 = new javax.swing.JToggleButton();
        cell18 = new javax.swing.JToggleButton();
        cell19 = new javax.swing.JToggleButton();
        cell20 = new javax.swing.JToggleButton();
        cell21 = new javax.swing.JToggleButton();
        cell22 = new javax.swing.JToggleButton();
        cell23 = new javax.swing.JToggleButton();
        cell24 = new javax.swing.JToggleButton();
        cell25 = new javax.swing.JToggleButton();
        cell26 = new javax.swing.JToggleButton();
        cell27 = new javax.swing.JToggleButton();
        cell28 = new javax.swing.JToggleButton();
        cell29 = new javax.swing.JToggleButton();
        cell30 = new javax.swing.JToggleButton();
        cell31 = new javax.swing.JToggleButton();
        cell32 = new javax.swing.JToggleButton();
        cell33 = new javax.swing.JToggleButton();
        cell34 = new javax.swing.JToggleButton();
        cell35 = new javax.swing.JToggleButton();
        cell36 = new javax.swing.JToggleButton();
        cell37 = new javax.swing.JToggleButton();
        cell38 = new javax.swing.JToggleButton();
        cell39 = new javax.swing.JToggleButton();
        cell40 = new javax.swing.JToggleButton();
        cell41 = new javax.swing.JToggleButton();
        cell42 = new javax.swing.JToggleButton();
        cell43 = new javax.swing.JToggleButton();
        cell44 = new javax.swing.JToggleButton();
        cell45 = new javax.swing.JToggleButton();
        cell46 = new javax.swing.JToggleButton();
        cell47 = new javax.swing.JToggleButton();
        cell48 = new javax.swing.JToggleButton();
        cell49 = new javax.swing.JToggleButton();
        cell50 = new javax.swing.JToggleButton();
        cell51 = new javax.swing.JToggleButton();
        cell52 = new javax.swing.JToggleButton();
        cell53 = new javax.swing.JToggleButton();
        cell54 = new javax.swing.JToggleButton();
        cell55 = new javax.swing.JToggleButton();
        cell56 = new javax.swing.JToggleButton();
        cell57 = new javax.swing.JToggleButton();
        cell58 = new javax.swing.JToggleButton();
        cell59 = new javax.swing.JToggleButton();
        cell60 = new javax.swing.JToggleButton();
        cell61 = new javax.swing.JToggleButton();
        cell62 = new javax.swing.JToggleButton();
        cell63 = new javax.swing.JToggleButton();
        cell64 = new javax.swing.JToggleButton();
        cell65 = new javax.swing.JToggleButton();
        cell66 = new javax.swing.JToggleButton();
        cell67 = new javax.swing.JToggleButton();
        cell68 = new javax.swing.JToggleButton();
        cell69 = new javax.swing.JToggleButton();
        cell70 = new javax.swing.JToggleButton();
        cell71 = new javax.swing.JToggleButton();
        cell72 = new javax.swing.JToggleButton();
        cell73 = new javax.swing.JToggleButton();
        cell74 = new javax.swing.JToggleButton();
        cell75 = new javax.swing.JToggleButton();
        cell76 = new javax.swing.JToggleButton();
        cell77 = new javax.swing.JToggleButton();
        cell78 = new javax.swing.JToggleButton();
        cell79 = new javax.swing.JToggleButton();
        cell80 = new javax.swing.JToggleButton();
        cell81 = new javax.swing.JToggleButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();

        setLayout(new java.awt.GridBagLayout());

        cell1.setFont(cell1.getFont().deriveFont(cell1.getFont().getStyle() | java.awt.Font.BOLD, cell1.getFont().getSize()+7));
        cell1.setText("1");
        cell1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell1.addActionListener(this::cell1ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        add(cell1, gridBagConstraints);

        cell2.setFont(cell2.getFont().deriveFont(cell2.getFont().getStyle() | java.awt.Font.BOLD, cell2.getFont().getSize()+7));
        cell2.setText("1");
        cell2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell2.addActionListener(this::cell2ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        add(cell2, gridBagConstraints);

        cell3.setFont(cell3.getFont().deriveFont(cell3.getFont().getStyle() | java.awt.Font.BOLD, cell3.getFont().getSize()+7));
        cell3.setText("1");
        cell3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell3.addActionListener(this::cell3ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        add(cell3, gridBagConstraints);

        cell4.setFont(cell4.getFont().deriveFont(cell4.getFont().getStyle() | java.awt.Font.BOLD, cell4.getFont().getSize()+7));
        cell4.setText("1");
        cell4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell4.addActionListener(this::cell4ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        add(cell4, gridBagConstraints);

        cell5.setFont(cell5.getFont().deriveFont(cell5.getFont().getStyle() | java.awt.Font.BOLD, cell5.getFont().getSize()+7));
        cell5.setText("1");
        cell5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell5.addActionListener(this::cell5ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        add(cell5, gridBagConstraints);

        cell6.setFont(cell6.getFont().deriveFont(cell6.getFont().getStyle() | java.awt.Font.BOLD, cell6.getFont().getSize()+7));
        cell6.setText("1");
        cell6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell6.addActionListener(this::cell6ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        add(cell6, gridBagConstraints);

        cell7.setFont(cell7.getFont().deriveFont(cell7.getFont().getStyle() | java.awt.Font.BOLD, cell7.getFont().getSize()+7));
        cell7.setText("1");
        cell7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell7.addActionListener(this::cell7ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        add(cell7, gridBagConstraints);

        cell8.setFont(cell8.getFont().deriveFont(cell8.getFont().getStyle() | java.awt.Font.BOLD, cell8.getFont().getSize()+7));
        cell8.setText("1");
        cell8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell8.addActionListener(this::cell8ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        add(cell8, gridBagConstraints);

        cell9.setFont(cell9.getFont().deriveFont(cell9.getFont().getStyle() | java.awt.Font.BOLD, cell9.getFont().getSize()+7));
        cell9.setText("1");
        cell9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell9.addActionListener(this::cell9ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        add(cell9, gridBagConstraints);

        cell10.setFont(cell10.getFont().deriveFont(cell10.getFont().getStyle() | java.awt.Font.BOLD, cell10.getFont().getSize()+7));
        cell10.setText("1");
        cell10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell10.addActionListener(this::cell10ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        add(cell10, gridBagConstraints);

        cell11.setFont(cell11.getFont().deriveFont(cell11.getFont().getStyle() | java.awt.Font.BOLD, cell11.getFont().getSize()+7));
        cell11.setText("1");
        cell11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell11.addActionListener(this::cell11ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        add(cell11, gridBagConstraints);

        cell12.setFont(cell12.getFont().deriveFont(cell12.getFont().getStyle() | java.awt.Font.BOLD, cell12.getFont().getSize()+7));
        cell12.setText("1");
        cell12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell12.addActionListener(this::cell12ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        add(cell12, gridBagConstraints);

        cell13.setFont(cell13.getFont().deriveFont(cell13.getFont().getStyle() | java.awt.Font.BOLD, cell13.getFont().getSize()+7));
        cell13.setText("1");
        cell13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell13.addActionListener(this::cell13ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        add(cell13, gridBagConstraints);

        cell14.setFont(cell14.getFont().deriveFont(cell14.getFont().getStyle() | java.awt.Font.BOLD, cell14.getFont().getSize()+7));
        cell14.setText("1");
        cell14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell14.addActionListener(this::cell14ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        add(cell14, gridBagConstraints);

        cell15.setFont(cell15.getFont().deriveFont(cell15.getFont().getStyle() | java.awt.Font.BOLD, cell15.getFont().getSize()+7));
        cell15.setText("1");
        cell15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell15.addActionListener(this::cell15ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        add(cell15, gridBagConstraints);

        cell16.setFont(cell16.getFont().deriveFont(cell16.getFont().getStyle() | java.awt.Font.BOLD, cell16.getFont().getSize()+7));
        cell16.setText("1");
        cell16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell16.addActionListener(this::cell16ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        add(cell16, gridBagConstraints);

        cell17.setFont(cell17.getFont().deriveFont(cell17.getFont().getStyle() | java.awt.Font.BOLD, cell17.getFont().getSize()+7));
        cell17.setText("1");
        cell17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell17.addActionListener(this::cell17ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        add(cell17, gridBagConstraints);

        cell18.setFont(cell18.getFont().deriveFont(cell18.getFont().getStyle() | java.awt.Font.BOLD, cell18.getFont().getSize()+7));
        cell18.setText("1");
        cell18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell18.addActionListener(this::cell18ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        add(cell18, gridBagConstraints);

        cell19.setFont(cell19.getFont().deriveFont(cell19.getFont().getStyle() | java.awt.Font.BOLD, cell19.getFont().getSize()+7));
        cell19.setText("1");
        cell19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell19.addActionListener(this::cell19ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        add(cell19, gridBagConstraints);

        cell20.setFont(cell20.getFont().deriveFont(cell20.getFont().getStyle() | java.awt.Font.BOLD, cell20.getFont().getSize()+7));
        cell20.setText("1");
        cell20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell20.addActionListener(this::cell20ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        add(cell20, gridBagConstraints);

        cell21.setFont(cell21.getFont().deriveFont(cell21.getFont().getStyle() | java.awt.Font.BOLD, cell21.getFont().getSize()+7));
        cell21.setText("1");
        cell21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell21.addActionListener(this::cell21ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        add(cell21, gridBagConstraints);

        cell22.setFont(cell22.getFont().deriveFont(cell22.getFont().getStyle() | java.awt.Font.BOLD, cell22.getFont().getSize()+7));
        cell22.setText("1");
        cell22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell22.addActionListener(this::cell22ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        add(cell22, gridBagConstraints);

        cell23.setFont(cell23.getFont().deriveFont(cell23.getFont().getStyle() | java.awt.Font.BOLD, cell23.getFont().getSize()+7));
        cell23.setText("1");
        cell23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell23.addActionListener(this::cell23ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        add(cell23, gridBagConstraints);

        cell24.setFont(cell24.getFont().deriveFont(cell24.getFont().getStyle() | java.awt.Font.BOLD, cell24.getFont().getSize()+7));
        cell24.setText("1");
        cell24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell24.addActionListener(this::cell24ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        add(cell24, gridBagConstraints);

        cell25.setFont(cell25.getFont().deriveFont(cell25.getFont().getStyle() | java.awt.Font.BOLD, cell25.getFont().getSize()+7));
        cell25.setText("1");
        cell25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell25.addActionListener(this::cell25ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        add(cell25, gridBagConstraints);

        cell26.setFont(cell26.getFont().deriveFont(cell26.getFont().getStyle() | java.awt.Font.BOLD, cell26.getFont().getSize()+7));
        cell26.setText("1");
        cell26.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell26.addActionListener(this::cell26ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        add(cell26, gridBagConstraints);

        cell27.setFont(cell27.getFont().deriveFont(cell27.getFont().getStyle() | java.awt.Font.BOLD, cell27.getFont().getSize()+7));
        cell27.setText("1");
        cell27.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell27.addActionListener(this::cell27ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        add(cell27, gridBagConstraints);

        cell28.setFont(cell28.getFont().deriveFont(cell28.getFont().getStyle() | java.awt.Font.BOLD, cell28.getFont().getSize()+7));
        cell28.setText("1");
        cell28.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell28.addActionListener(this::cell28ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        add(cell28, gridBagConstraints);

        cell29.setFont(cell29.getFont().deriveFont(cell29.getFont().getStyle() | java.awt.Font.BOLD, cell29.getFont().getSize()+7));
        cell29.setText("1");
        cell29.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell29.addActionListener(this::cell29ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        add(cell29, gridBagConstraints);

        cell30.setFont(cell30.getFont().deriveFont(cell30.getFont().getStyle() | java.awt.Font.BOLD, cell30.getFont().getSize()+7));
        cell30.setText("1");
        cell30.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell30.addActionListener(this::cell30ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        add(cell30, gridBagConstraints);

        cell31.setFont(cell31.getFont().deriveFont(cell31.getFont().getStyle() | java.awt.Font.BOLD, cell31.getFont().getSize()+7));
        cell31.setText("1");
        cell31.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell31.addActionListener(this::cell31ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        add(cell31, gridBagConstraints);

        cell32.setFont(cell32.getFont().deriveFont(cell32.getFont().getStyle() | java.awt.Font.BOLD, cell32.getFont().getSize()+7));
        cell32.setText("1");
        cell32.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell32.addActionListener(this::cell32ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        add(cell32, gridBagConstraints);

        cell33.setFont(cell33.getFont().deriveFont(cell33.getFont().getStyle() | java.awt.Font.BOLD, cell33.getFont().getSize()+7));
        cell33.setText("1");
        cell33.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell33.addActionListener(this::cell33ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        add(cell33, gridBagConstraints);

        cell34.setFont(cell34.getFont().deriveFont(cell34.getFont().getStyle() | java.awt.Font.BOLD, cell34.getFont().getSize()+7));
        cell34.setText("1");
        cell34.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell34.addActionListener(this::cell34ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        add(cell34, gridBagConstraints);

        cell35.setFont(cell35.getFont().deriveFont(cell35.getFont().getStyle() | java.awt.Font.BOLD, cell35.getFont().getSize()+7));
        cell35.setText("1");
        cell35.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell35.addActionListener(this::cell35ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        add(cell35, gridBagConstraints);

        cell36.setFont(cell36.getFont().deriveFont(cell36.getFont().getStyle() | java.awt.Font.BOLD, cell36.getFont().getSize()+7));
        cell36.setText("1");
        cell36.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell36.addActionListener(this::cell36ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        add(cell36, gridBagConstraints);

        cell37.setFont(cell37.getFont().deriveFont(cell37.getFont().getStyle() | java.awt.Font.BOLD, cell37.getFont().getSize()+7));
        cell37.setText("1");
        cell37.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell37.addActionListener(this::cell37ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        add(cell37, gridBagConstraints);

        cell38.setFont(cell38.getFont().deriveFont(cell38.getFont().getStyle() | java.awt.Font.BOLD, cell38.getFont().getSize()+7));
        cell38.setText("1");
        cell38.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell38.addActionListener(this::cell38ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        add(cell38, gridBagConstraints);

        cell39.setFont(cell39.getFont().deriveFont(cell39.getFont().getStyle() | java.awt.Font.BOLD, cell39.getFont().getSize()+7));
        cell39.setText("1");
        cell39.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell39.addActionListener(this::cell39ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        add(cell39, gridBagConstraints);

        cell40.setFont(cell40.getFont().deriveFont(cell40.getFont().getStyle() | java.awt.Font.BOLD, cell40.getFont().getSize()+7));
        cell40.setText("1");
        cell40.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell40.addActionListener(this::cell40ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        add(cell40, gridBagConstraints);

        cell41.setFont(cell41.getFont().deriveFont(cell41.getFont().getStyle() | java.awt.Font.BOLD, cell41.getFont().getSize()+7));
        cell41.setText("1");
        cell41.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell41.addActionListener(this::cell41ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        add(cell41, gridBagConstraints);

        cell42.setFont(cell42.getFont().deriveFont(cell42.getFont().getStyle() | java.awt.Font.BOLD, cell42.getFont().getSize()+7));
        cell42.setText("1");
        cell42.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell42.addActionListener(this::cell42ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        add(cell42, gridBagConstraints);

        cell43.setFont(cell43.getFont().deriveFont(cell43.getFont().getStyle() | java.awt.Font.BOLD, cell43.getFont().getSize()+7));
        cell43.setText("1");
        cell43.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell43.addActionListener(this::cell43ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        add(cell43, gridBagConstraints);

        cell44.setFont(cell44.getFont().deriveFont(cell44.getFont().getStyle() | java.awt.Font.BOLD, cell44.getFont().getSize()+7));
        cell44.setText("1");
        cell44.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell44.addActionListener(this::cell44ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        add(cell44, gridBagConstraints);

        cell45.setFont(cell45.getFont().deriveFont(cell45.getFont().getStyle() | java.awt.Font.BOLD, cell45.getFont().getSize()+7));
        cell45.setText("1");
        cell45.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell45.addActionListener(this::cell45ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        add(cell45, gridBagConstraints);

        cell46.setFont(cell46.getFont().deriveFont(cell46.getFont().getStyle() | java.awt.Font.BOLD, cell46.getFont().getSize()+7));
        cell46.setText("1");
        cell46.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell46.addActionListener(this::cell46ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        add(cell46, gridBagConstraints);

        cell47.setFont(cell47.getFont().deriveFont(cell47.getFont().getStyle() | java.awt.Font.BOLD, cell47.getFont().getSize()+7));
        cell47.setText("1");
        cell47.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell47.addActionListener(this::cell47ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        add(cell47, gridBagConstraints);

        cell48.setFont(cell48.getFont().deriveFont(cell48.getFont().getStyle() | java.awt.Font.BOLD, cell48.getFont().getSize()+7));
        cell48.setText("1");
        cell48.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell48.addActionListener(this::cell48ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        add(cell48, gridBagConstraints);

        cell49.setFont(cell49.getFont().deriveFont(cell49.getFont().getStyle() | java.awt.Font.BOLD, cell49.getFont().getSize()+7));
        cell49.setText("1");
        cell49.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell49.addActionListener(this::cell49ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        add(cell49, gridBagConstraints);

        cell50.setFont(cell50.getFont().deriveFont(cell50.getFont().getStyle() | java.awt.Font.BOLD, cell50.getFont().getSize()+7));
        cell50.setText("1");
        cell50.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell50.addActionListener(this::cell50ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        add(cell50, gridBagConstraints);

        cell51.setFont(cell51.getFont().deriveFont(cell51.getFont().getStyle() | java.awt.Font.BOLD, cell51.getFont().getSize()+7));
        cell51.setText("1");
        cell51.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell51.addActionListener(this::cell51ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        add(cell51, gridBagConstraints);

        cell52.setFont(cell52.getFont().deriveFont(cell52.getFont().getStyle() | java.awt.Font.BOLD, cell52.getFont().getSize()+7));
        cell52.setText("1");
        cell52.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell52.addActionListener(this::cell52ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        add(cell52, gridBagConstraints);

        cell53.setFont(cell53.getFont().deriveFont(cell53.getFont().getStyle() | java.awt.Font.BOLD, cell53.getFont().getSize()+7));
        cell53.setText("1");
        cell53.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell53.addActionListener(this::cell53ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        add(cell53, gridBagConstraints);

        cell54.setFont(cell54.getFont().deriveFont(cell54.getFont().getStyle() | java.awt.Font.BOLD, cell54.getFont().getSize()+7));
        cell54.setText("1");
        cell54.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell54.addActionListener(this::cell54ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        add(cell54, gridBagConstraints);

        cell55.setFont(cell55.getFont().deriveFont(cell55.getFont().getStyle() | java.awt.Font.BOLD, cell55.getFont().getSize()+7));
        cell55.setText("1");
        cell55.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell55.addActionListener(this::cell55ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        add(cell55, gridBagConstraints);

        cell56.setFont(cell56.getFont().deriveFont(cell56.getFont().getStyle() | java.awt.Font.BOLD, cell56.getFont().getSize()+7));
        cell56.setText("1");
        cell56.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell56.addActionListener(this::cell56ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        add(cell56, gridBagConstraints);

        cell57.setFont(cell57.getFont().deriveFont(cell57.getFont().getStyle() | java.awt.Font.BOLD, cell57.getFont().getSize()+7));
        cell57.setText("1");
        cell57.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell57.addActionListener(this::cell57ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        add(cell57, gridBagConstraints);

        cell58.setFont(cell58.getFont().deriveFont(cell58.getFont().getStyle() | java.awt.Font.BOLD, cell58.getFont().getSize()+7));
        cell58.setText("1");
        cell58.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell58.addActionListener(this::cell58ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        add(cell58, gridBagConstraints);

        cell59.setFont(cell59.getFont().deriveFont(cell59.getFont().getStyle() | java.awt.Font.BOLD, cell59.getFont().getSize()+7));
        cell59.setText("1");
        cell59.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell59.addActionListener(this::cell59ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        add(cell59, gridBagConstraints);

        cell60.setFont(cell60.getFont().deriveFont(cell60.getFont().getStyle() | java.awt.Font.BOLD, cell60.getFont().getSize()+7));
        cell60.setText("1");
        cell60.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell60.addActionListener(this::cell60ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        add(cell60, gridBagConstraints);

        cell61.setFont(cell61.getFont().deriveFont(cell61.getFont().getStyle() | java.awt.Font.BOLD, cell61.getFont().getSize()+7));
        cell61.setText("1");
        cell61.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell61.addActionListener(this::cell61ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        add(cell61, gridBagConstraints);

        cell62.setFont(cell62.getFont().deriveFont(cell62.getFont().getStyle() | java.awt.Font.BOLD, cell62.getFont().getSize()+7));
        cell62.setText("1");
        cell62.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell62.addActionListener(this::cell62ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        add(cell62, gridBagConstraints);

        cell63.setFont(cell63.getFont().deriveFont(cell63.getFont().getStyle() | java.awt.Font.BOLD, cell63.getFont().getSize()+7));
        cell63.setText("1");
        cell63.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell63.addActionListener(this::cell63ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        add(cell63, gridBagConstraints);

        cell64.setFont(cell64.getFont().deriveFont(cell64.getFont().getStyle() | java.awt.Font.BOLD, cell64.getFont().getSize()+7));
        cell64.setText("1");
        cell64.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell64.addActionListener(this::cell64ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        add(cell64, gridBagConstraints);

        cell65.setFont(cell65.getFont().deriveFont(cell65.getFont().getStyle() | java.awt.Font.BOLD, cell65.getFont().getSize()+7));
        cell65.setText("1");
        cell65.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell65.addActionListener(this::cell65ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        add(cell65, gridBagConstraints);

        cell66.setFont(cell66.getFont().deriveFont(cell66.getFont().getStyle() | java.awt.Font.BOLD, cell66.getFont().getSize()+7));
        cell66.setText("1");
        cell66.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell66.addActionListener(this::cell66ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        add(cell66, gridBagConstraints);

        cell67.setFont(cell67.getFont().deriveFont(cell67.getFont().getStyle() | java.awt.Font.BOLD, cell67.getFont().getSize()+7));
        cell67.setText("1");
        cell67.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell67.addActionListener(this::cell67ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        add(cell67, gridBagConstraints);

        cell68.setFont(cell68.getFont().deriveFont(cell68.getFont().getStyle() | java.awt.Font.BOLD, cell68.getFont().getSize()+7));
        cell68.setText("1");
        cell68.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell68.addActionListener(this::cell68ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        add(cell68, gridBagConstraints);

        cell69.setFont(cell69.getFont().deriveFont(cell69.getFont().getStyle() | java.awt.Font.BOLD, cell69.getFont().getSize()+7));
        cell69.setText("1");
        cell69.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell69.addActionListener(this::cell69ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        add(cell69, gridBagConstraints);

        cell70.setFont(cell70.getFont().deriveFont(cell70.getFont().getStyle() | java.awt.Font.BOLD, cell70.getFont().getSize()+7));
        cell70.setText("1");
        cell70.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell70.addActionListener(this::cell70ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        add(cell70, gridBagConstraints);

        cell71.setFont(cell71.getFont().deriveFont(cell71.getFont().getStyle() | java.awt.Font.BOLD, cell71.getFont().getSize()+7));
        cell71.setText("1");
        cell71.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell71.addActionListener(this::cell71ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        add(cell71, gridBagConstraints);

        cell72.setFont(cell72.getFont().deriveFont(cell72.getFont().getStyle() | java.awt.Font.BOLD, cell72.getFont().getSize()+7));
        cell72.setText("1");
        cell72.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell72.addActionListener(this::cell72ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        add(cell72, gridBagConstraints);

        cell73.setFont(cell73.getFont().deriveFont(cell73.getFont().getStyle() | java.awt.Font.BOLD, cell73.getFont().getSize()+7));
        cell73.setText("1");
        cell73.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell73.addActionListener(this::cell73ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        add(cell73, gridBagConstraints);

        cell74.setFont(cell74.getFont().deriveFont(cell74.getFont().getStyle() | java.awt.Font.BOLD, cell74.getFont().getSize()+7));
        cell74.setText("1");
        cell74.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell74.addActionListener(this::cell74ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        add(cell74, gridBagConstraints);

        cell75.setFont(cell75.getFont().deriveFont(cell75.getFont().getStyle() | java.awt.Font.BOLD, cell75.getFont().getSize()+7));
        cell75.setText("1");
        cell75.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell75.addActionListener(this::cell75ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        add(cell75, gridBagConstraints);

        cell76.setFont(cell76.getFont().deriveFont(cell76.getFont().getStyle() | java.awt.Font.BOLD, cell76.getFont().getSize()+7));
        cell76.setText("1");
        cell76.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell76.addActionListener(this::cell76ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        add(cell76, gridBagConstraints);

        cell77.setFont(cell77.getFont().deriveFont(cell77.getFont().getStyle() | java.awt.Font.BOLD, cell77.getFont().getSize()+7));
        cell77.setText("1");
        cell77.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell77.addActionListener(this::cell77ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        add(cell77, gridBagConstraints);

        cell78.setFont(cell78.getFont().deriveFont(cell78.getFont().getStyle() | java.awt.Font.BOLD, cell78.getFont().getSize()+7));
        cell78.setText("1");
        cell78.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell78.addActionListener(this::cell78ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        add(cell78, gridBagConstraints);

        cell79.setFont(cell79.getFont().deriveFont(cell79.getFont().getStyle() | java.awt.Font.BOLD, cell79.getFont().getSize()+7));
        cell79.setText("1");
        cell79.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell79.addActionListener(this::cell79ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        add(cell79, gridBagConstraints);

        cell80.setFont(cell80.getFont().deriveFont(cell80.getFont().getStyle() | java.awt.Font.BOLD, cell80.getFont().getSize()+7));
        cell80.setText("1");
        cell80.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell80.addActionListener(this::cell80ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        add(cell80, gridBagConstraints);

        cell81.setFont(cell81.getFont().deriveFont(cell81.getFont().getStyle() | java.awt.Font.BOLD, cell81.getFont().getSize()+7));
        cell81.setText("1");
        cell81.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell81.addActionListener(this::cell81ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        add(cell81, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 11;
        gridBagConstraints.ipady = 2;
        add(jSeparator1, gridBagConstraints);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 11;
        gridBagConstraints.ipadx = 2;
        add(jSeparator2, gridBagConstraints);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 11;
        gridBagConstraints.ipadx = 2;
        add(jSeparator3, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 11;
        gridBagConstraints.ipady = 2;
        add(jSeparator6, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void cell1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cell1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cell1ActionPerformed

    private void cell2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cell2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cell2ActionPerformed

    private void cell3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cell3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cell3ActionPerformed

    private void cell4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cell4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cell4ActionPerformed

    private void cell5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cell5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cell5ActionPerformed

    private void cell6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cell6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cell6ActionPerformed

    private void cell7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cell7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cell7ActionPerformed

    private void cell8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cell8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cell8ActionPerformed

    private void cell9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cell9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cell9ActionPerformed

    private void cell10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cell10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cell10ActionPerformed

    private void cell11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cell11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cell11ActionPerformed

    private void cell12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cell12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cell12ActionPerformed

    private void cell13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cell13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cell13ActionPerformed

    private void cell14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cell14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cell14ActionPerformed

    private void cell15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cell15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cell15ActionPerformed

    private void cell16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cell16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cell16ActionPerformed

    private void cell17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cell17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cell17ActionPerformed

    private void cell18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cell18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cell18ActionPerformed

    private void cell19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cell19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cell19ActionPerformed

    private void cell20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cell20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cell20ActionPerformed

    private void cell21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cell21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cell21ActionPerformed

    private void cell22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cell22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cell22ActionPerformed

    private void cell23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cell23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cell23ActionPerformed

    private void cell24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cell24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cell24ActionPerformed

    private void cell25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cell25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cell25ActionPerformed

    private void cell26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cell26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cell26ActionPerformed

    private void cell27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cell27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cell27ActionPerformed

    private void cell28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cell28ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cell28ActionPerformed

    private void cell29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cell29ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cell29ActionPerformed

    private void cell30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cell30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cell30ActionPerformed

    private void cell31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cell31ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cell31ActionPerformed

    private void cell32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cell32ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cell32ActionPerformed

    private void cell33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cell33ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cell33ActionPerformed

    private void cell34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cell34ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cell34ActionPerformed

    private void cell35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cell35ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cell35ActionPerformed

    private void cell36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cell36ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cell36ActionPerformed

    private void cell37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cell37ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cell37ActionPerformed

    private void cell38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cell38ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cell38ActionPerformed

    private void cell39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cell39ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cell39ActionPerformed

    private void cell40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cell40ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cell40ActionPerformed

    private void cell41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cell41ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cell41ActionPerformed

    private void cell42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cell42ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cell42ActionPerformed

    private void cell43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cell43ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cell43ActionPerformed

    private void cell44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cell44ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cell44ActionPerformed

    private void cell45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cell45ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cell45ActionPerformed

    private void cell46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cell46ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cell46ActionPerformed

    private void cell47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cell47ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cell47ActionPerformed

    private void cell48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cell48ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cell48ActionPerformed

    private void cell49ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cell49ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cell49ActionPerformed

    private void cell50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cell50ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cell50ActionPerformed

    private void cell51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cell51ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cell51ActionPerformed

    private void cell52ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cell52ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cell52ActionPerformed

    private void cell53ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cell53ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cell53ActionPerformed

    private void cell54ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cell54ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cell54ActionPerformed

    private void cell55ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cell55ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cell55ActionPerformed

    private void cell56ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cell56ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cell56ActionPerformed

    private void cell57ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cell57ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cell57ActionPerformed

    private void cell58ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cell58ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cell58ActionPerformed

    private void cell59ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cell59ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cell59ActionPerformed

    private void cell60ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cell60ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cell60ActionPerformed

    private void cell61ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cell61ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cell61ActionPerformed

    private void cell62ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cell62ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cell62ActionPerformed

    private void cell63ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cell63ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cell63ActionPerformed

    private void cell64ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cell64ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cell64ActionPerformed

    private void cell65ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cell65ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cell65ActionPerformed

    private void cell66ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cell66ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cell66ActionPerformed

    private void cell67ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cell67ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cell67ActionPerformed

    private void cell68ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cell68ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cell68ActionPerformed

    private void cell69ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cell69ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cell69ActionPerformed

    private void cell70ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cell70ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cell70ActionPerformed

    private void cell71ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cell71ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cell71ActionPerformed

    private void cell72ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cell72ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cell72ActionPerformed

    private void cell73ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cell73ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cell73ActionPerformed

    private void cell74ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cell74ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cell74ActionPerformed

    private void cell75ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cell75ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cell75ActionPerformed

    private void cell76ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cell76ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cell76ActionPerformed

    private void cell77ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cell77ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cell77ActionPerformed

    private void cell78ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cell78ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cell78ActionPerformed

    private void cell79ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cell79ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cell79ActionPerformed

    private void cell80ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cell80ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cell80ActionPerformed

    private void cell81ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cell81ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cell81ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton cell1;
    private javax.swing.JToggleButton cell10;
    private javax.swing.JToggleButton cell11;
    private javax.swing.JToggleButton cell12;
    private javax.swing.JToggleButton cell13;
    private javax.swing.JToggleButton cell14;
    private javax.swing.JToggleButton cell15;
    private javax.swing.JToggleButton cell16;
    private javax.swing.JToggleButton cell17;
    private javax.swing.JToggleButton cell18;
    private javax.swing.JToggleButton cell19;
    private javax.swing.JToggleButton cell2;
    private javax.swing.JToggleButton cell20;
    private javax.swing.JToggleButton cell21;
    private javax.swing.JToggleButton cell22;
    private javax.swing.JToggleButton cell23;
    private javax.swing.JToggleButton cell24;
    private javax.swing.JToggleButton cell25;
    private javax.swing.JToggleButton cell26;
    private javax.swing.JToggleButton cell27;
    private javax.swing.JToggleButton cell28;
    private javax.swing.JToggleButton cell29;
    private javax.swing.JToggleButton cell3;
    private javax.swing.JToggleButton cell30;
    private javax.swing.JToggleButton cell31;
    private javax.swing.JToggleButton cell32;
    private javax.swing.JToggleButton cell33;
    private javax.swing.JToggleButton cell34;
    private javax.swing.JToggleButton cell35;
    private javax.swing.JToggleButton cell36;
    private javax.swing.JToggleButton cell37;
    private javax.swing.JToggleButton cell38;
    private javax.swing.JToggleButton cell39;
    private javax.swing.JToggleButton cell4;
    private javax.swing.JToggleButton cell40;
    private javax.swing.JToggleButton cell41;
    private javax.swing.JToggleButton cell42;
    private javax.swing.JToggleButton cell43;
    private javax.swing.JToggleButton cell44;
    private javax.swing.JToggleButton cell45;
    private javax.swing.JToggleButton cell46;
    private javax.swing.JToggleButton cell47;
    private javax.swing.JToggleButton cell48;
    private javax.swing.JToggleButton cell49;
    private javax.swing.JToggleButton cell5;
    private javax.swing.JToggleButton cell50;
    private javax.swing.JToggleButton cell51;
    private javax.swing.JToggleButton cell52;
    private javax.swing.JToggleButton cell53;
    private javax.swing.JToggleButton cell54;
    private javax.swing.JToggleButton cell55;
    private javax.swing.JToggleButton cell56;
    private javax.swing.JToggleButton cell57;
    private javax.swing.JToggleButton cell58;
    private javax.swing.JToggleButton cell59;
    private javax.swing.JToggleButton cell6;
    private javax.swing.JToggleButton cell60;
    private javax.swing.JToggleButton cell61;
    private javax.swing.JToggleButton cell62;
    private javax.swing.JToggleButton cell63;
    private javax.swing.JToggleButton cell64;
    private javax.swing.JToggleButton cell65;
    private javax.swing.JToggleButton cell66;
    private javax.swing.JToggleButton cell67;
    private javax.swing.JToggleButton cell68;
    private javax.swing.JToggleButton cell69;
    private javax.swing.JToggleButton cell7;
    private javax.swing.JToggleButton cell70;
    private javax.swing.JToggleButton cell71;
    private javax.swing.JToggleButton cell72;
    private javax.swing.JToggleButton cell73;
    private javax.swing.JToggleButton cell74;
    private javax.swing.JToggleButton cell75;
    private javax.swing.JToggleButton cell76;
    private javax.swing.JToggleButton cell77;
    private javax.swing.JToggleButton cell78;
    private javax.swing.JToggleButton cell79;
    private javax.swing.JToggleButton cell8;
    private javax.swing.JToggleButton cell80;
    private javax.swing.JToggleButton cell81;
    private javax.swing.JToggleButton cell9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator6;
    // End of variables declaration//GEN-END:variables
}
